### ISSUE TITLE
Compound Queries with Prefix Matching?

### ISSUE THREAD

**Issue by ssandeep** [StevenJL/rawscsi#1]
Does this gem support compound queries with prefix matching as given here:
http://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-text.html#searching-text-prefixes

**Comment by StevenJL** [comment]
@ssandeep , the latest version (1.1.0) now also supports prefix matching, thanks to @azolotko.  You can see the syntax here: https://github.com/StevenJL/rawscsi#prefix-matching
