### ISSUE TITLE
Phrase query support

### ISSUE THREAD

**Issue by epaminond** [StevenJL/rawscsi#13]
Is there support for [phrase queries](https://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-compound-queries.html) like `(and (phrase field='title' 'star wars')`?

**Comment by StevenJL** [comment]
no, but you wanna help with that? :smile_cat:

**Comment by StevenJL** [comment]
Here's the PR for it: https://github.com/StevenJL/rawscsi/pull/20
